name: Build

on:
  push:
    branches:
      - master
      - 'develop-*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout humblenet
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build humblenet
        uses: urkle/action-cmake-build@feat-wrapper-command
        with:
          run-test: true
          parallel: 1

  build_emscripten:
    runs-on: ubuntu-latest
    env:
      EM_VERSION: 1.39.20
      EM_CACHE_FOLDER: 'emsdk-cache'
    steps:
      - name: Checkout humblenet
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache flatbuffers
        id: cache-flatbuffers
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/external/flatbuffers/
          key: ${{ runner.os }}-flatbuffers-${{ hashFiles('3rdparty/flatbuffers/includes/base.h') }}
      - name: build flatbuffers
        if: steps.cache-flatbuffers.outputs.cache-hit != 'true'
        uses: urkle/action-cmake-build@feat-wrapper-command
        with:
          source-dir: ${{ github.workspace }}/3rdparty/flatbuffers/
          build-dir: ${{ github.workspace }}/3rdparty/flatbuffers/cmake-build/
          configure-options: -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/external/flatbuffers/
          install-build: true

      - name: Cache emsdk
        uses: actions/cache@v2
        id: emsdk-cache
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{ runner.os }}-emsdk-${{env.EM_VERSION}}
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: build humblenet (emscripten)
        uses: urkle/action-cmake-build@feat-wrapper-command
        with:
          wrapper-command: emcmake
          configure-options: -DCMAKE_PREFIX_PATH=${{ github.workspace }}/external/flatbuffers/
          parallel: 1
